version: '3'
services:
  # web-dev:
  #   build: 
  #     context: .
  #     dockerfile: Dockerfile.dev
  #   ports: 
  #     - "3000:3000"
  #   volumes: 
  #     - /app/node_modules
  #     - .:/usr/app
  #   command: ["npm", "run", "start"]
  # web-tests:
  #   build: 
  #     context: .
  #     dockerfile: Dockerfile.dev
  #   volumes: 
  #     - /app/node_modules
  #     - .:/usr/app
  #   command: ["npm", "run", "test"]
  web-build:
    build: 
      context: .
      dockerfile: Dockerfile
    command: ["npm", "run", "build"]